# Contents for Python Makefile 
PY = python3

all: server client

# make sure TAs can make server/client/clean
server:
client:
clean:

run-server: 
	$(PY) $< server.py 127.1 9012

run-client: 
	$(PY) $< client.py 127.1 9012


run-server-e:
	$(PY) $< server-e.py 127.1 9012

run-client-e:
	$(PY) $< client-e.py 127.1 9012
	